# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"\"\n\x0c\x41udioRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\"\'\n\x10\x44\x65\x65pfakeResponse\x12\x13\n\x0bis_deepfake\x18\x01 \x01(\x08\x32W\n\tInference\x12J\n\x0e\x43lassifyStream\x12\x17.inference.AudioRequest\x1a\x1b.inference.DeepfakeResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOREQUEST']._serialized_start=30
  _globals['_AUDIOREQUEST']._serialized_end=64
  _globals['_DEEPFAKERESPONSE']._serialized_start=66
  _globals['_DEEPFAKERESPONSE']._serialized_end=105
  _globals['_INFERENCE']._serialized_start=107
  _globals['_INFERENCE']._serialized_end=194
# @@protoc_insertion_point(module_scope)
